---

name: Tests
run-name: ${{ gitea.actor }} tests
on:
  push:
  pull_request:
  workflow_call:

jobs:
  tests:
    runs-on: docker
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    container:
      image: codeberg.org/readeck/readeck-ci:latest
      volumes:
        - go-readability:/workspace
      env:
        HOME: /workspace
        GOPATH: /workspace/go
        GOCACHE: /workspace/.cache/go-build
        GOLANGCI_LINT_CACHE: /workspace/.cache/golangci-lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint
        shell: bash
        run: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6 run .

      - name: Run tests
        shell: bash
        run: go test -v -timeout 30s ./...
